# Generated by Django 5.0.3 on 2026-02-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='code',
            new_name='otp',
        ),
    ]
