# Generated by Django 5.0.3 on 2026-03-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_code_otpcode_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('item', models.CharField(max_length=250)),
                ('total', models.IntegerField()),
                ('allocated', models.IntegerField()),
                ('available', models.IntegerField()),
                ('utilization', models.IntegerField()),
                ('status', models.CharField(choices=[('In Stock', 'in stock'), ('Out Of Stock', 'out of stock')], default='In Stock', max_length=250)),
            ],
        ),
    ]
