# Generated by Django 5.0.3 on 2026-03-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_allocated_alter_inventory_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_configuration', models.CharField(choices=[('Full Allocation Report', 'Full Allocation Report'), ('Available Stock Summary', 'Available Stock Summary'), ('User Specific Report', 'User Specific Report')], default='Full Allocation Report', max_length=256)),
                ('date_range', models.CharField(choices=[('All Time', 'All Time'), ('Last 7 Days', 'Last 7 Days'), ('Last 30 Days', 'Last 30 Days'), ('This Month', 'This Month')], default='All Time', max_length=256)),
                ('export_format', models.CharField(choices=[('csv', '.csv — Comma Separated'), ('xlsx', '.xlsx — Excel'), ('pdf', '.pdf — PDF')], default='csv', max_length=50)),
            ],
        ),
    ]
