# Generated by Django 5.0.3 on 2026-03-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_utilization_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reservations', to='inventory.user'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reservations', to='inventory.inventory'),
        ),
    ]
