# Generated by Django 5.0.3 on 2026-03-09 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_reservation_email_alter_reservation_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='item',
            new_name='inventory',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_reservations', to='inventory.user'),
            preserve_default=False,
        ),
    ]
