# Generated by Django 5.0.3 on 2026-03-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_item_reservation_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
